// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4ljwrxVmzw4GoGvo1ZYby0V8-154t5JE',
    appId: '1:145616314978:web:3c3bdf0a9e586aeed2673b',
    messagingSenderId: '145616314978',
    projectId: 'avaliacao-3-31b9d',
    authDomain: 'avaliacao-3-31b9d.firebaseapp.com',
    storageBucket: 'avaliacao-3-31b9d.firebasestorage.app',
    measurementId: 'G-H1DSZYBRND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdXDtVAwrZVGQvMgSuqnxplZGEK68qbTg',
    appId: '1:145616314978:android:c3b5075f22a0bf49d2673b',
    messagingSenderId: '145616314978',
    projectId: 'avaliacao-3-31b9d',
    storageBucket: 'avaliacao-3-31b9d.firebasestorage.app',
  );

}